### ISSUE TITLE
[Bug] command 'blockman.toggleEnableDisable' not found

### ISSUE THREAD

**Issue by mmailaender** [leodevbro/vscode-blockman#102]
After installing Blockman, I tried to activate it, but it failed with this error message:
![image](https://user-images.githubusercontent.com/87228994/222102800-d483a99f-f17e-4d7e-bd45-6cdc813975f6.png)

I'm using Gitpod 
![image](https://user-images.githubusercontent.com/87228994/222104914-8d177b19-510a-4d41-bef0-e7bed5990243.png)

And Blockman version 1.7.1 (https://open-vsx.org/vscode/item?itemName=leodevbro.blockman)

![image](https://user-images.githubusercontent.com/87228994/222103045-b85f3dcb-fcf6-47e0-b6c7-6805f40fd8fc.png)

My settings.json:

```
{
  "typescript.tsdk": "node_modules/typescript/lib",
  "gitlens.showWelcomeOnInstall": false,
  "gitlens.showWhatsNewAfterUpgrades": true,
  "gitlens.virtualRepositories.enabled": false,
  "files.autoSave": "onFocusChange",
  "typescript.enablePromptUseWorkspaceTsdk": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "javascript.suggest.paths": false,
  "typescript.suggest.paths": false,
  "editor.linkedEditing": true,

  // Configuration for Blockman
  "editor.inlayHints.enabled": "off",
  "editor.guides.indentation": false,
  "diffEditor.wordWrap": "off",
  "workbench.colorCustomizations": {
    "editor.lineHighlightBorder": "#9fced11f",
    "editor.lineHighlightBackground": "#1073cf2d"
  }
}
```

My extensions:
![image](https://user-images.githubusercontent.com/87228994/222104770-194b4e9f-2bc5-465d-9486-797e96291e3a.png)

Tested also with Blockman version 1.6.5 and 1.5.9 (Same result)

**Comment by leodevbro** [comment]
Hello, sorry for late reply. Unfortunately I don't know what could be the cause of this error. In the source code of Blockman, everything seems fine (screenshot bellow), and this command works fine on my machine (Windows 11). I think it's a bug of VS Code (Linux) itself. Maybe you can try reinstalling VS Code.

![image](https://user-images.githubusercontent.com/54504880/222508068-8dadbd11-86d9-4fb3-beb1-bcc9f97c8046.png)

**Comment by mmailaender** [comment]
Unfortunately, I can't - It's from [GitPod](https://www.gitpod.io/). But I created a Bug report there and linked it to this one.

**Comment by mmailaender** [comment]
Do you think it's possible with some manageble efforts to add support for VS code web?

**Comment by leodevbro** [comment]
>Do you think it's possible with some manageble efforts to add support for VS code web?

I already put so much effort, I tried many things in the code. The problem is parser/tokenizer libraries. Some of them works only in Node.js environment. I even contacted Microsoft team on Github and asked them to give extensions access to native tokens of VS Code, so Blockman would not need any third party library for it. But, It seems they think it's too difficult (or too unsafe) thing to implement in extension API:
https://github.com/microsoft/vscode/issues/131062


Now, soon, I'm going to create another feature request on the VS Code github repo where I will explain more clearly that it's worth implementing such feature in the extension API of VS Code.

**Comment by jeanp413** [comment]
@leodevbro you can use `vscode.env.uiKind` to check if it's running on desktop or browser and then search in  `node_modules` instead of `node_modules.asar`

**Comment by leodevbro** [comment]
@jeanp413, The thing is that Blockman uses WASM, so it's not so easy to just have usual node_modules.
It uses WASM for bracket (curly/square/round) tokenization.

**Comment by leodevbro** [comment]
Right now I posted a feature request in the VS Code GitHub repo. If this feature request get green light, then Blockman will most likely be able to run in browser.

https://github.com/microsoft/vscode/issues/177452

**Comment by jeanp413** [comment]
I think your confusing vscode web extensions with running vscode in the browser, it's not the same:
- you can run vscode in the browser connected to a remote server (e.g gitpod.io) so extensions can use `node_modules`
- you can also run vscode serverless like github.dev or vscode.dev in this case only web extension are allowed and need a `browser` entrypoint in package.json

Created a PR https://github.com/leodevbro/vscode-blockman/pull/103 so it works in the first case
