### ISSUE TITLE
VSCode setting to disable set up message during start

### ISSUE THREAD

**Issue by mmailaender** [leodevbro/vscode-blockman#104]
We're using Gitpod. Gitpod are ephemeral development instances. That means Blockman will be installed every time fresh when I start a new GitPod instance. It would be great to have a setting, to suppress the initial set-up message:

![image](https://user-images.githubusercontent.com/87228994/225993825-c27bf92d-bc07-4b50-835e-1a9fe62a6748.png)

**Comment by leodevbro** [comment]
Thanks for the information. I'll try to fix it tomorrow.

**Comment by leodevbro** [comment]
I'll try to fix it as soon as I can. Unfortunately now I have some strong difficulties to find time to sit down and check out my projects. Probably I will have more time after 1-2 weeks.

**Comment by leodevbro** [comment]
Hi, I think I fixed it. With new version (1.7.3) of Blockman, you can go to VS Code settings,
and search:
`blockman n35 a01 disable recommendation dialog `

Check it.
Done.

**Comment by mmailaender** [comment]
Yes, it's working - Thank you so much! ❤️
