### ISSUE TITLE
Latest version doesn't work.

### ISSUE THREAD

**Issue by SaidTorres3** [leodevbro/vscode-blockman#108]
The latest version (1.7.2) doesn't work for me. This is the error I get in the developer tools:

![image](https://user-images.githubusercontent.com/65783413/228678862-ea9a8b72-c30d-4cc0-8f8d-04b2bbf58fcc.png)

I tried to reinstall it multiple times, but it doesn't work.

If I install the previous version (1.7.1) it works.

**Comment by leodevbro** [comment]
Please provide you system info:

OS, VS Code version, and where is the VS Code running? In your local computer or in remote service like Gitpod?
