### ISSUE TITLE
Not working at all!

### ISSUE THREAD

**Issue by TaylorJeromeHawkins** [leodevbro/vscode-blockman#114]
Tried installing and reinstalling but no luck getting the extension to work. Tried a bunch of settings mentioned in the documentation but no luck. Would love to try this extension!

**Comment by leodevbro** [comment]
Hi, I noticed this problem several times, but it is very rare. And mostly restarting VS Code fixes it. And also please make sure that Blockman is not disabled by the F1 command: `blockman toggle enable/disable`.

Maybe you can also try restarting the computer entirely.

Also you can try installing it on VS Code Insiders.

**Comment by TaylorJeromeHawkins** [comment]
Thanks!

The restart worked, but it isn't working for my html files for some reason. Great extension from what I can see so far!

**Comment by leodevbro** [comment]
Each line should have less than 3000 characters, otherwise Blockman will not render anywthing.

If it's not the case, please provide the HTML file so I will be able to test it myself.

**Comment by TaylorJeromeHawkins** [comment]
I have a few paths > 3000. That must be the issue! Thank you!

**Comment by leodevbro** [comment]
I decided to set the 3000 limit because long lines are most likely minified code, and there is almost no point to render blocks of minified code. But if you think that this limit should be increased a little, please tell me. Maybe to 4000? How long is the longest path in your HTML files?

**Comment by leodevbro** [comment]
I updated Blockman. With the new version (1.7.4) you can change this setting:
`Blockman: N36 A01 Max Char Count In Any Line`
Default is 3000, you can set any number.

**Comment by TaylorJeromeHawkins** [comment]
Awesome, great work thank you!
