### ISSUE TITLE
Background color of entire file being overwritten to near-black

### ISSUE THREAD

**Issue by darkvertex** [leodevbro/vscode-blockman#12]
My theme is supposed to give me a light grey'ish tone but after installing Blockman it's almost total black and it's really distracting.

Is there any way to get the blocks drawn on top of the chosen theme as it exists?

**Comment by leodevbro** [comment]
Did not you see the GIFs in Blockman page? You can customize colors in many many many maaaany ways. You can type any rgba() color or any css color in depth0 color field in Blockman settings. Or you can just type "none" in the depth0 color field, so the background color of depth0 (ground block) will be fully transparent and the vscode theme background will show up. You can also change colors in each depth. Just play around Blockman settings.

**Comment by darkvertex** [comment]
Ah okay! It wasn't clear to me that "none" was a valid color. (Is that mentioned somewhere? Could be good to put in the prefs text at least.)

I'd also add that it would be a little clearer if "Custom Color" said "Custom BG Color". It's not obvious until scrolling 10 settings down that the color is not for the border, but the background of the block.

Anyway, thanks to your tip I've found the combo that gives me what I expected the extension's defaults to be:
```
    "blockman.n05CustomColorOfDepth0": "none",
    "blockman.n10CustomColorOfDepth5": "none",
    "blockman.n09CustomColorOfDepth4": "none",
    "blockman.n07CustomColorOfDepth2": "none",
    "blockman.n08CustomColorOfDepth3": "none",
    "blockman.n06CustomColorOfDepth1": "none",
    "blockman.n12CustomColorOfDepth7": "none",
    "blockman.n13CustomColorOfDepth8": "none",
    "blockman.n11CustomColorOfDepth6": "none",
    "blockman.n14CustomColorOfDepth9": "none",
    "blockman.n15CustomColorOfDepth10": "none",
    "blockman.n17CustomColorOfFocusedBlock": "same",
    "blockman.n20CustomColorOfDepth0Border": "none",
```

Thanks!

**Comment by leodevbro** [comment]
Well, "none" is just arbitrary word. It is not actually valid, that's why no color is rendering. The valid way of "none" would be something like rgba(0, 0, 0, 0) which is also supported by Blockman, but "none" is shorter and works fine.
