### ISSUE TITLE
Feature Request: Whitelist

### ISSUE THREAD

**Issue by hk21702** [leodevbro/vscode-blockman#130]
I know that there exists a blacklist already, but it would be really nice to also have a whitelist for specific file formats.

**Comment by leodevbro** [comment]
Hello @hk21702, Blockman now supports white list of file formats. Current version is `v1.7.6` (2024-02-01).

in `blockman.n32BlackListOfFileFormats` (**Blockman: N32 Black List Of File Formats**)

Just type ‘^’ (caret symbol) at the left of the list, and it will become a white list. 
Like this: 
`^ typescript, typescriptreact`

**Comment by hk21702** [comment]
Works great for me! Thanks.
