### ISSUE TITLE
Visual issue with inline parameter

### ISSUE THREAD

**Issue by bumpyy** [leodevbro/vscode-blockman#132]
![Code_wN3dcasXif](https://github.com/leodevbro/vscode-blockman/assets/28483765/d86e3657-27ae-4d7d-92bc-c4b1c15fe436)

So, I'm using [inline parameter by Liam hammet](https://marketplace.visualstudio.com/items?itemName=liamhammett.inline-parameters) and it causes some sort of visual bug?, anyway it's fine if i hide the inline parameter.
![Code_d7hhqh2Kic](https://github.com/leodevbro/vscode-blockman/assets/28483765/f8373386-b9ae-4cad-8252-400d975f97c4)

Anyway, just letting you know, cheers 🥂.

**Comment by leodevbro** [comment]
Hello, unfortunately this is a VS Code limitation for extensions that extensions are not able to know where are the inlay hints placed or what are the widths of each inlay hint, or where do the actual code characters are located. Blockman calculates locations of letters by count of letters and the monospace-width of a letter.

If you use inlay hints, then for a bit better experience, probably it's a good idea to set Blockman setting of:
`blockman.n04Sub04RightSideBaseOfBlocks`
to `Rightmost Edge Of Viewport`.
By default, it is `Rightmost Edge Of Inner Content`.

More info:
https://github.com/leodevbro/vscode-blockman/issues/84

.

https://github.com/leodevbro/vscode-blockman/issues/99

.
.
