### ISSUE TITLE
Rightmost Edge of Viewport no longer works on the latest VSCode version

### ISSUE THREAD

**Issue by justinsako** [leodevbro/vscode-blockman#135]
While this setting has been working just fine, after updating VSCode recently (currently on 1.88.0), the "Rightmost Edge of Viewport" is now creating this mess:

![image](https://github.com/leodevbro/vscode-blockman/assets/2652342/8c943029-3055-4f08-b8f5-e88ceb66a6a5)

The "Rightmost Edge of Inner Content" and "Rightmost Edge of File Content" seems to continue working correctly.

**Comment by leodevbro** [comment]
Thanks for reporting. Probably it's a new bug of VS Code. I'll try to fix it myself or maybe I'll post a bug report in VS Code GitHub repo.

Meanwhile, maybe it will be relatively fine for your taste to set `Rightmost Edge Of File Content` or `Rightmost Edge Of Inner Content`.

**Comment by leodevbro** [comment]
@justinsako, Hi, I think I fixed the `Rightmost Edge of Viewport` - the new version of Blockman is `v1.7.7` (2024-04-20). Please verify that it is fixed.

**Comment by justinsako** [comment]
Look like it is working again. Thank you!
