### ISSUE TITLE
How do I change my settings if I use settings.json?

### ISSUE THREAD

**Issue by jcklpe** [leodevbro/vscode-blockman#15]
The readme shows exclusively the changing of settings through the GUI. I prefer to use text based configs because I can version control them, and more explicitly write out the exact changes I want.   
  
There is no real explanation of how to do this in the readme though. Please consider adding this information.

**Comment by leodevbro** [comment]
Just open settings.json and type `"Blockman."` and it will show the second part of the setting name. Also you can change any setting in GUI and it will automatically show up in settings.json file.

**Comment by jcklpe** [comment]
@leodevbro : that's good to know but it might still be something useful to add to the actual README.

**Comment by leodevbro** [comment]
Instructions of using text based configs is not specific to Blockman itself, it is general VSCode feature, so I don't think that Blockman DEADME page needs such instructions. Anyone can learn VSCode features in official docs and Youtube videos.

**Comment by cschweda** [comment]
Agree with @jcklpe. Always good to add this stuff to the readme -- event if it's in official docs or YouTube videos.

Can't hurt -- and it'll only increase downloads.

**Comment by leodevbro** [comment]
@jcklpe, @cschweda,
I updated Blockman (v1.2.8). Added text based config in README. You can just search `All Blockman settings`.
