### ISSUE TITLE
How do I set overwidth on purpose? I would like to increase the negative space of the containers

### ISSUE THREAD

**Issue by jcklpe** [leodevbro/vscode-blockman#16]
I like the idea of this a lot and in my own personal set up I have used several different extensions to mark out the block scope visually. I am testing out blockman, and I like it's basic idea but I would like if I could set more negative space or padding in the container. As it is now things feel too close to the edge of the container.   
  
In the art world this concept is know as a tangent composition mistake: [https://willkempartschool.com/compostional-mistakes-in-drawing/](https://willkempartschool.com/compostional-mistakes-in-drawing/)

**Comment by leodevbro** [comment]
Padding is interesting but there are many cases where it is impossible, for example:
![2021-05-31_20-08-36](https://user-images.githubusercontent.com/54504880/121790761-bdfe8e80-cbf3-11eb-8394-6101caab3652.png)

**Comment by jcklpe** [comment]
@leodevbro   : What is the issue that makes it impossible?   
  
I ask in part because this issue of "adding padding to extension styling" is something that I've run up against a couple of times in my experiments editing vscode visuals.

**Comment by leodevbro** [comment]
For example, single line blocks are mostly impossible to add padding.
![image](https://user-images.githubusercontent.com/54504880/122636276-713a1c80-d0f9-11eb-82b6-4f395a2e71b2.png)

**Comment by jcklpe** [comment]
It would also be possible to only add the padding for non single lines right? 

I am asking this question partially because I'm curious about the limitations in general for adding padding in vscode visual presentation. A single line with padding potentially doesn't work because adding padding would throw off the monospacing right?

**Comment by leodevbro** [comment]
Yeah, and sometimes multi-line blocks are also very limited to add any padding.
![image](https://user-images.githubusercontent.com/54504880/126889310-7f274be4-b0b2-4a31-be89-e24caad6da57.png)

**Comment by leodevbro** [comment]
@jcklpe, I think I implemented the block-expanding/padding (**only right side**) settings.
The latest version of Blockman is 1.5.1 (2022-01-19).

![right-side-padding-strategies-2-gif](https://user-images.githubusercontent.com/54504880/150204474-647609ad-8428-4762-b276-a84439640b9c.gif)

**Comment by jcklpe** [comment]
This is great! thank you so much @leodevbro !
