### ISSUE TITLE
Support for `editor.letterSpacing`

### ISSUE THREAD

**Issue by MartialSeron** [leodevbro/vscode-blockman#17]
I use a monotype font but with a modified letter spacing property the text is wider than the block

Without `editor.letterSpacing`
![image](https://user-images.githubusercontent.com/5698488/121895132-2d719c80-cd20-11eb-8207-b4551a3c32df.png)

With `editor.letterSpacing`
![image](https://user-images.githubusercontent.com/5698488/121895508-978a4180-cd20-11eb-93b2-6b81b882d00c.png)

**Comment by leodevbro** [comment]
I think I fixed it now. The latest version is 1.1.6 (2021-06-15).
