### ISSUE TITLE
Disable certain depth levels ( specifically Depth0 )

### ISSUE THREAD

**Issue by alvarezdqal** [leodevbro/vscode-blockman#19]
I would prefer for the lowest depth to not be outlined. In Python, there doesn't seem to be any advantage in having the whole module outlined.

Could you introduce the ability to ignore certain depths?
```json
{
    "blockman.ignoredDepths": [
        0,
        1
    ]
}
```

Or perhaps to specify a range of depths that the user would like to outline?

```json
{
    "blockman.range": "2:8"
}
```

**Comment by leodevbro** [comment]
You can hide the block of depth0 (ground block). Just go to Blockman settings and type "none" in depth0-color field, and type "none" in N20 (depth0 border) color field. You can also type any rgb()/hsl() color in each depth-color field, there are depth color fields from 0 to 10. There is also more other settings. **Did not you see the GIFs on Blockman page?**
