### ISSUE TITLE
Add support for newer version of VS code to install the extension.

### ISSUE THREAD

**Issue by Bsmalhi** [leodevbro/vscode-blockman#24]
![Screen Shot 2021-06-21 at 6 27 14 PM](https://user-images.githubusercontent.com/11641321/122848403-4fd65d80-d2be-11eb-8d58-c1d32b27691d.png)

As you can see the screenshot while installing this extension on my Mac VS Code it throws the error about not compatible which is a blocker to install and use such a nice extension.

VScode details
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:06:21.189Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0

**Comment by leodevbro** [comment]
The latest version of VSCode is 1.57.1, you have 1.56.0, so please update VSCode, restart VSCode and try installing Blockman again.
