### ISSUE TITLE
Theme issues

### ISSUE THREAD

**Issue by sahil48** [leodevbro/vscode-blockman#27]
I installed blockman, and when a txt file was set as a django txt Language Mode, the background of text turned from blue to white

before
![image](https://user-images.githubusercontent.com/6100774/123837171-86bcfc80-d8d8-11eb-9052-409a70aea67c.png)

after
![image](https://user-images.githubusercontent.com/6100774/123837187-8d4b7400-d8d8-11eb-925b-98b5d0b43c26.png)

**Comment by sahil48** [comment]
Theme is oceanic plus

**Comment by sahil48** [comment]
Theme is oceanic plus

**Comment by leodevbro** [comment]
Can you check the value of Color Combo in Blockman settings? Myybe it's "Classic Light" somehow?
Maybe you need to set it as "Classic Dark".
![image](https://user-images.githubusercontent.com/54504880/123837870-644cd280-d91c-11eb-8b74-242ece7270f4.png)

**Comment by sahil48** [comment]
That fixed it. Thanks or such a quick response. I appreciate it.

Do you have any Color Combos with just the border and no change to the background color? I feel like that may blend in better with more colorful themes.

**Comment by leodevbro** [comment]
Welcome. If you want to hide all backgrounds and keep only borders, you can go to Blockman settings and type "none" in all depth-color fields. There are 11 depth-color fields, from 0 to 10.

If you want custom color for border, you can type any css color value into the "**N19 Custom Color Of Block Border**".
