### ISSUE TITLE
Feature request: only show blocks for current scope tree

### ISSUE THREAD

**Issue by bbugh** [leodevbro/vscode-blockman#28]
Nice extension! 

I'd love if there was a toggle to only show blocks for the current scope. It would make it a lot easier to know where the cursor is and help understand the code I'm working on actively, while ignoring the rest.

I think this would help performance too.

Thanks for reading!

**Comment by leodevbro** [comment]
Currently there is not a toggle for such case, but you can go to Blockman settings and type "none" in all depth-color fields. There are 11 depth-color fields, from 0 to 10.

Also you can type "none" in N19 (border color) field and N20 (depth0 border color) fields.

And, so, only the focused block will be visible.

**Comment by leodevbro** [comment]
@bbugh, I did not understand the request first time, but now I understand. I'll think about implementing it. If it's not a huge brain pain, then maybe I'll be able to do it in several days.

**Comment by leodevbro** [comment]
@bbugh, Blockman 1.4.0 (already 1.4.1) is now released. Here is the video instruction for the advanced coloring settings:

https://www.youtube.com/watch?v=UsET6-kPu90

If you find it difficult to adjust the settings exactly for your needs, please let me know and I will help you with the instructions specifically for your cases.

**Comment by leodevbro** [comment]
https://github.com/leodevbro/vscode-blockman/issues/97
