### ISSUE TITLE
Feature Request: Whitelist and/or blacklist for file types

### ISSUE THREAD

**Issue by Meltz014** [leodevbro/vscode-blockman#3]
It'd be nice to be able to disable certain file extensions that get rendered.

**Comment by leodevbro** [comment]
Thanks, I think I can do it very soon.

**Comment by leodevbro** [comment]
I'm just interested, which file extensions would you like to be in black list? and why?

**Comment by leodevbro** [comment]
Currently (from version 1.1.4) you can quickly toggle enable/disable Blockman: Press F1 and then type "blockman toggle".

**Comment by leodevbro** [comment]
I updated Blockman to 1.2.0, now you can set Black List Of File Formats in Blockman settings.
