### ISSUE TITLE
how to disable the color and just enable the square box only

### ISSUE THREAD

**Issue by heartacker** [leodevbro/vscode-blockman#32]
THANKS

**Comment by leodevbro** [comment]
If you want to hide all backgrounds and keep borders only, go to Blockman settings and type "none" in all depth color fields. There are 11 depth-color fields, from 0 to 10.

**Comment by heartacker** [comment]
> If you want to hide all backgrounds and keep borders only, go to Blockman settings and type "none" in all depth color fields. There are 11 depth-color fields, from 0 to 10.

 Well, thanks.
 And I hope that it will be an option for people to  disable it directly.

**Comment by leodevbro** [comment]
I'll try to make it for the next update of Blockman.

**Comment by leodevbro** [comment]
With new version of Blockman, it has now additional advanced coloring settings, so you can disable all backgrounds more easily. Just open Blockman settings, find:

`N33 A01 B2`

and type:

`10, 0, 0, 2; none`
