### ISSUE TITLE
Border do not match correctly if the font size if too big or small

### ISSUE THREAD

**Issue by tyk198** [leodevbro/vscode-blockman#33]
Border work correctly when font size is normal
![image](https://user-images.githubusercontent.com/85450973/126194224-0e69af0d-7988-4dd3-9896-97ac6e54038a.png)

But border work incorrectly when the font size is too big
![image](https://user-images.githubusercontent.com/85450973/126192126-22c1410a-fa09-4035-95c1-70b3a78ff5f4.png)

How should I fixed this?

**Comment by leodevbro** [comment]
Please provide detailed info:
* Editor: Font Family
* Editor: Font Size
* Editor: Mouse Wheel Zoom -> ON or OFF ?
* Window: Zoom Level

Also please make sure that **if** Workspace settings (or folder settings) are overriding User settings, provide Workspace settings (or folder settings).

**Comment by tyk198** [comment]
Editor: Font Family: Consolas, 'Courier New', monospace
Editor: 14
Editor: Mouse Wheel Zoom -> ON 
Window: Fullscreen

**Comment by tyk198** [comment]
Changing the font size at setting does not solve the problem, does not matter at what font size, when using the mouse wheel to change font size, the bottom border will off by about one line, weather the font become smaller or bigger by using mouse wheel. However,  if the font size is medium(not using mouse wheel to change it to too small or big) the border will work correctly. The top, left and right sides of border has no problem, it is just bottom does not work correctly. I always change font size to write code, so it is bothering me.

**Comment by leodevbro** [comment]
Now I see. well, it is the VSCode limitation, not a bug of Blockman.
VSCode does not give us access to line height pixel value when we zoom/unzoom with mouse wheel.

Here is the issue: https://github.com/microsoft/vscode/issues/125341#issuecomment-854962933

**Comment by tyk198** [comment]
I see, maybe you could try and guest the multiplayer of the zoom value? I am not sure how it work.

**Comment by tyk198** [comment]
So changing the zoom level of window and font size does not affect how the border work, only when changing font size with mouse wheel will affect it. Is there a way to change font size in setting by using mouse wheel?

**Comment by leodevbro** [comment]
That's interesting proposal. I'm not sure vscode API supports such functionality. You can ask this question in the vscode repo.

**Comment by tyk198** [comment]
I had found an extension to change font size with shortcut, it now works properly for me. Thank you for helping me out, this project is really helpful and amazing!

**Comment by leodevbro** [comment]
@tyk198, Very good news: I fixed the mouse wheel zoom behavior of Blockman. It should work fine now. The latest Version of Blockman is `1.4.5 (2022-01-03)`
