### ISSUE TITLE
Need Display Support

### ISSUE THREAD

**Issue by arthasxkyang** [leodevbro/vscode-blockman#35]
When Chinese characters are included in a line, the width of the BLOCK cannot be expanded correctly.

For example, when I text in such below,

class 新建自定义类(socketserver.BaseRequestHandler):

The BLOCK seems to ignore the Chinese in this line, showing the wrong width, which is significantly shorter than the length of the row.

Great plugin by the way, thank you for your contribution.
Hope to get support soon.

**Comment by leodevbro** [comment]
That's not a bug of Blockman, it's the limitation of VSCode API. It does not gives us access to the pixel locations of the characters, so the only think an extension can do is to compute width by number of characters, so the font must be monospace.

But there is a chance of solution to your specific case.
Press F1 and type `blockman toggle try support double width chars`
![image](https://user-images.githubusercontent.com/54504880/126894069-ee80695f-d6c7-40c0-87ac-f22fa56b39cd.png)

**Comment by arthasxkyang** [comment]
This solution works! Thanks for help.

Though it still doesn't quite match the width (this time it be a little wider), 
it's already made me feel comfortable enough at work. XD
