### ISSUE TITLE
Highlight Disappers with SVG in code

### ISSUE THREAD

**Issue by r00sn** [leodevbro/vscode-blockman#36]
I'm no sure if it's just me, but when I have `<svg></svg>` in my code all the highlight blocks disappear. As soon as I get rid of the svg block the highlight comes back.

**Comment by leodevbro** [comment]
Can you provide the entire file code? (with svg included)

**Comment by r00sn** [comment]
Please find the code below:

`    
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <svg id="bg_image" xmlns="http://www.w3.org/2000/svg" >
    <g>
        <path d="M467.16,380c-36.46,0-70.85-7.36-96-12.74-13.56-2.91-24.27-5.2-30.31-5.2a12.14,12.14,0,0,0-3,.3c-19.07,5.08-34.76,7.45-49.37,7.45a125.32,125.32,0,0,1-38.85-6.09c-27-8.66-43.73-31.1-43.73-58.57s16.76-49.9,43.73-58.56a125.32,125.32,0,0,1,38.85-6.09c14.61,0,30.3,2.36,49.37,7.45a12.14,12.14,0,0,0,3,.3c6,0,16.75-2.29,30.31-5.2,25.11-5.38,59.5-12.74,96-12.74,23.77,0,45.43,3.24,64.41,9.63,12-3.5,22.41-5.21,31.88-5.21,19.3,0,30.08,7.28,38.73,13.13,3.77,2.55,7,4.75,10.45,6,5.83,2.19,12.29,3.12,21.63,3.12,4.91,0,10.26-.24,16.45-.52,8-.36,17.11-.76,27.9-.76,15,0,51.58,7.87,68.32,17.57,2.27,1.31,4.55,2.55,6.75,3.74,12.06,6.53,23.46,12.7,23.46,28.11s-11.4,21.59-23.46,28.12c-2.2,1.19-4.48,2.43-6.75,3.74-15.59,9-47.09,17.89-63.61,17.89a32.38,32.38,0,0,1-5-.34c-14.56-2.31-25.67-3.74-36.06-3.74-11.32,0-20.7,1.76-29.52,5.56a59.32,59.32,0,0,0-9.64,5.84c-8.68,6-19.49,13.46-39.11,13.46-9.59,0-20.19-1.74-32.4-5.31C512.6,376.75,490.93,380,467.16,380Z" fill="#f2f2f2"/>
        <path d="M467.16,232.3c21.43,0,43.45,2.59,64.36,9.73,12.85-3.81,23.28-5.31,31.93-5.31,27,0,36.6,14.58,48.48,19,6.73,2.52,13.81,3.24,22.33,3.24,11.37,0,25.3-1.28,44.35-1.28,14.44,0,51,7.84,67.32,17.3,14.83,8.59,29.21,13.29,29.21,30.12s-14.38,21.54-29.21,30.13-46.17,17.62-62.61,17.62a30.32,30.32,0,0,1-4.71-.32c-13.55-2.15-25.43-3.76-36.37-3.76-10.77,0-20.64,1.56-30.31,5.72-11.58,5-21.29,19.14-48,19.14-8.76,0-19.35-1.53-32.45-5.41-20.91,7.14-42.93,9.73-64.36,9.73-56.43,0-108.78-17.94-126.27-17.94a14,14,0,0,0-3.52.37c-17.39,4.63-33.29,7.38-48.86,7.38a123.23,123.23,0,0,1-38.24-6c-24.74-7.93-42.34-28.56-42.34-56.66s17.6-48.72,42.34-56.65a123.23,123.23,0,0,1,38.24-6c15.57,0,31.46,2.74,48.86,7.38a14,14,0,0,0,3.52.37c17.48,0,69.84-17.94,126.27-17.94m0-4c-36.67,0-71.18,7.39-96.38,12.79-13.44,2.88-24.06,5.15-29.89,5.15a10.38,10.38,0,0,1-2.49-.23c-19.24-5.13-35.1-7.52-49.89-7.52a127.12,127.12,0,0,0-39.46,6.19c-27.83,8.93-45.12,32.1-45.12,60.46s17.29,51.54,45.12,60.47a127.12,127.12,0,0,0,39.46,6.19c14.79,0,30.65-2.39,49.89-7.52a10.38,10.38,0,0,1,2.49-.23c5.83,0,16.45,2.27,29.89,5.15C396,374.6,430.49,382,467.16,382c23.74,0,45.41-3.21,64.45-9.54,12.14,3.51,22.74,5.22,32.36,5.22,20.24,0,31.33-7.66,40.25-13.82a57.12,57.12,0,0,1,9.29-5.64c8.56-3.69,17.69-5.4,28.73-5.4,10.26,0,21.28,1.42,35.74,3.71a34.07,34.07,0,0,0,5.34.37c16.79,0,48.79-9,64.61-18.16,2.25-1.3,4.51-2.52,6.7-3.71,12.61-6.82,24.51-13.26,24.51-29.88s-11.9-23.05-24.51-29.87c-2.19-1.19-4.45-2.41-6.7-3.71-17-9.85-54.11-17.84-69.32-17.84-10.84,0-20,.41-28,.76-6.17.28-11.49.52-16.36.52-9.08,0-15.34-.89-20.92-3-3.21-1.2-6.37-3.34-10-5.82-8.88-6-19.93-13.47-39.85-13.47-9.5,0-19.93,1.68-31.84,5.12-19-6.33-40.71-9.54-64.45-9.54Z" fill="gray"/>
    </g>

    </svg>  
    
</body>
</html>
 `

**Comment by leodevbro** [comment]
This is because Blockman does not render blocks if there is any line with more that 500 characters (Maybe I will increase this limit to 2000 in the next update of Blockman). The path strings in your svg code are more than 500 chars.

For now, maybe you can keep these long strings in a separate file like this:
```
const longs = {
    path1:
        "M467.16,380c-36.46,0-70.85-7.36-96-12.74-13.56-2.91-24.27-5.2-30.31-5.2a12.14,12.14,0,0,0-3,.3c-19.07,5.08-34.76,7.45-49.37,7.45a125.32,125.32,0,0,1-38.85-6.09c-27-8.66-43.73-31.1-43.73-58.57s16.76-49.9,43.73-58.56a125.32,125.32,0,0,1,38.85-6.09c14.61,0,30.3,2.36,49.37,7.45a12.14,12.14,0,0,0,3,.3c6,0,16.75-2.29,30.31-5.2,25.11-5.38,59.5-12.74,96-12.74,23.77,0,45.43,3.24,64.41,9.63,12-3.5,22.41-5.21,31.88-5.21,19.3,0,30.08,7.28,38.73,13.13,3.77,2.55,7,4.75,10.45,6,5.83,2.19,12.29,3.12,21.63,3.12,4.91,0,10.26-.24,16.45-.52,8-.36,17.11-.76,27.9-.76,15,0,51.58,7.87,68.32,17.57,2.27,1.31,4.55,2.55,6.75,3.74,12.06,6.53,23.46,12.7,23.46,28.11s-11.4,21.59-23.46,28.12c-2.2,1.19-4.48,2.43-6.75,3.74-15.59,9-47.09,17.89-63.61,17.89a32.38,32.38,0,0,1-5-.34c-14.56-2.31-25.67-3.74-36.06-3.74-11.32,0-20.7,1.76-29.52,5.56a59.32,59.32,0,0,0-9.64,5.84c-8.68,6-19.49,13.46-39.11,13.46-9.59,0-20.19-1.74-32.4-5.31C512.6,376.75,490.93,380,467.16,380Z",
    path2:
        "M467.16,232.3c21.43,0,43.45,2.59,64.36,9.73,12.85-3.81,23.28-5.31,31.93-5.31,27,0,36.6,14.58,48.48,19,6.73,2.52,13.81,3.24,22.33,3.24,11.37,0,25.3-1.28,44.35-1.28,14.44,0,51,7.84,67.32,17.3,14.83,8.59,29.21,13.29,29.21,30.12s-14.38,21.54-29.21,30.13-46.17,17.62-62.61,17.62a30.32,30.32,0,0,1-4.71-.32c-13.55-2.15-25.43-3.76-36.37-3.76-10.77,0-20.64,1.56-30.31,5.72-11.58,5-21.29,19.14-48,19.14-8.76,0-19.35-1.53-32.45-5.41-20.91,7.14-42.93,9.73-64.36,9.73-56.43,0-108.78-17.94-126.27-17.94a14,14,0,0,0-3.52.37c-17.39,4.63-33.29,7.38-48.86,7.38a123.23,123.23,0,0,1-38.24-6c-24.74-7.93-42.34-28.56-42.34-56.66s17.6-48.72,42.34-56.65a123.23,123.23,0,0,1,38.24-6c15.57,0,31.46,2.74,48.86,7.38a14,14,0,0,0,3.52.37c17.48,0,69.84-17.94,126.27-17.94m0-4c-36.67,0-71.18,7.39-96.38,12.79-13.44,2.88-24.06,5.15-29.89,5.15a10.38,10.38,0,0,1-2.49-.23c-19.24-5.13-35.1-7.52-49.89-7.52a127.12,127.12,0,0,0-39.46,6.19c-27.83,8.93-45.12,32.1-45.12,60.46s17.29,51.54,45.12,60.47a127.12,127.12,0,0,0,39.46,6.19c14.79,0,30.65-2.39,49.89-7.52a10.38,10.38,0,0,1,2.49-.23c5.83,0,16.45,2.27,29.89,5.15C396,374.6,430.49,382,467.16,382c23.74,0,45.41-3.21,64.45-9.54,12.14,3.51,22.74,5.22,32.36,5.22,20.24,0,31.33-7.66,40.25-13.82a57.12,57.12,0,0,1,9.29-5.64c8.56-3.69,17.69-5.4,28.73-5.4,10.26,0,21.28,1.42,35.74,3.71a34.07,34.07,0,0,0,5.34.37c16.79,0,48.79-9,64.61-18.16,2.25-1.3,4.51-2.52,6.7-3.71,12.61-6.82,24.51-13.26,24.51-29.88s-11.9-23.05-24.51-29.87c-2.19-1.19-4.45-2.41-6.7-3.71-17-9.85-54.11-17.84-69.32-17.84-10.84,0-20,.41-28,.76-6.17.28-11.49.52-16.36.52-9.08,0-15.34-.89-20.92-3-3.21-1.2-6.37-3.34-10-5.82-8.88-6-19.93-13.47-39.85-13.47-9.5,0-19.93,1.68-31.84,5.12-19-6.33-40.71-9.54-64.45-9.54Z",
};
```

and then, if you are using react.js, you can insert them into the svg:

```
<svg id="bg_image" xmlns="http://www.w3.org/2000/svg" >
    <g>
        <path d={longs.path1} fill="#f2f2f2"/>
        <path d={longs.path2} fill="gray"/>
    </g>
</svg>  
```

**Comment by r00sn** [comment]
@leodevbro Got it. Appreciate your advice.
