### ISSUE TITLE
Feature: Support to SQL language

### ISSUE THREAD

**Issue by carlosdan-el** [leodevbro/vscode-blockman#38]
Hello! I'd like to use Blockman with SQL language (e.g.: Stored Procedures, Functions, Views).
Will be useful in large SQL code.

**Comment by leodevbro** [comment]
Thanks for feedback.
For now, let's close this issue, because is seems same as this issue:
https://github.com/leodevbro/vscode-blockman/issues/39

And please see my replies there.
