### ISSUE TITLE
Support for SQL Queries

### ISSUE THREAD

**Issue by gleysonlf** [leodevbro/vscode-blockman#39]
I would like to congratulate you for the tool, very good!
Secondly, I would like to suggest support for SQL queries, many people have been using VSCode as their default editor and many procedures give developers a headache.

**Comment by leodevbro** [comment]
Thanks...
Have you tried to enable round brackets like this?

https://raw.githubusercontent.com/leodevbro/vscode-blockman/main/demo-media/video/settings/based-on-bracket-types---c2-apng.png
