### ISSUE TITLE
Indent guide issues after uninstalling

### ISSUE THREAD

**Issue by enkia** [leodevbro/vscode-blockman#4]
After uninstalling Blockman, my indent guide color doesn't revert back to what it is in the theme I'm using which should be:
`"editorIndentGuide.activeBackground": "#363b54",`

Also, the vscode setting "Highlight Active Indent Guide" stops working since your style shows either way.

**Comment by leodevbro** [comment]
Hi, Blockman does not touch `"editorIndentGuide.activeBackground"` at all. I cannot tell why the color of indent guide changed.

`"Highlight Active Indent Guide"` stops working? What do you mean "stops working"? Blockman just turns off it, you can just turn it back on anytime. Or, maybe you also need to turn on `"editor.renderIndentGuides"`.

**Comment by enkia** [comment]
My bad, I meant:
```
"editor.lineHighlightBackground": "#1073cf2d",
"editor.lineHighlightBorder": "#9fced11f"
```

But I see now how it added a setting.  Disregard!
