### ISSUE TITLE
Feature request: Start one block per line

### ISSUE THREAD

**Issue by ThaJay** [leodevbro/vscode-blockman#42]
I noticed two blocks get rendered on the same line if mutiple block tokens are found there, while only one block is needed:
![image](https://user-images.githubusercontent.com/9341747/132326444-e0f7f552-3b96-4e6f-9d9f-7855601e4fae.png)

**Comment by leodevbro** [comment]
I don't see any issues here. What do you mean `only one block is needed` ?

You have turned on analyzing `square` brackets. Maybe you could turn it off and keep only analyzing `curly` brackets turned on. So, the blocks won't be too overloaded. But anyway, the blocks are rendering correctly as I see in the image.

**Comment by ThaJay** [comment]
On the top left before 'issued_date', the the purple bracket starts a block instead of the purple curly brace after `function`, which would correspond with the end of the block. In this situation it would seem more logical to me to use the yellow bracket and the if statement for a block. Right now it looks a bit inconsistent starting at the second bracket and ending at the last curly brace.

**Comment by leodevbro** [comment]
No, the start indicator of the block is not the purple brackets. The start indicator is the yellow bracket. You can test it, just write anything between the yellow and the purple brackets, for example a comment like this: `/*commnet*/`.

And also, the end indicator of the block is not the last curly bracket. It's the last yellow square bracket. You can test it, just write  `/*commnet*/` between them.

**Comment by ThaJay** [comment]
Ah I see, it looks like that because there is no newline after the yellow bracket. It seems to me that a block is only needed when a newline follows a block token, but that may not work for all code bases.

Prettier would have probably added a newline after the yellow bracket, after the comma before function and after the last curly brace so it seems to be mostly down to bad formatting here.

**Comment by ThaJay** [comment]
This looks much better
![image](https://user-images.githubusercontent.com/9341747/132473525-fd16917a-d247-4f9e-8755-2a37c5e1f0c6.png)
