### ISSUE TITLE
How to enable this extension?

### ISSUE THREAD

**Issue by notes365** [leodevbro/vscode-blockman#5]
I installed it and didn't see the effect

![image](https://user-images.githubusercontent.com/51652878/120897337-28de2180-c658-11eb-91d3-3886eb62b87c.png)

**Comment by leodevbro** [comment]
Maybe that's because you have installed Bracket Pair Colorizer, try uninstalling BPC. Sometimes it prevents Blockman to work, but I don't know why.

**Comment by notes365** [comment]
Yes, I disable the Bracket Pair Colorizer and it works normally

**Comment by notes365** [comment]
you can make Bracket Pair Colorizer part of the blockman

**Comment by leodevbro** [comment]
Well, I think Blockman and Bracket Pair Colorizer works fine together, it's Bracket Pair Colorizer 2 which is the problem. Blockman and Bracket Pair Colorizer 2 sometimes conflict each other, maybe because BPC2 is currently beta and maybe buggy.
