### ISSUE TITLE
Reverse Rendering Order for  Gradients

### ISSUE THREAD

**Issue by Cicin411** [leodevbro/vscode-blockman#51]
Could the tool give a options , using Reverse Order for  rendering ?
Which means, the focused block order number = 0
then the outer =1, then 2 , then 3....

**Comment by leodevbro** [comment]
The question is: what to render when nothing is focused?

**Comment by Cicin411** [comment]
> The question is: what to render when nothing is focused?

For me, rendering nothing or as the way as now. They are both ok.  
Options may work well for tasting differ.
Maybe rendering everything then the whold document will be so dazing.
I just care about the blocks I want to focus on, and the blocks focused should be highlighter than outer regions.
At least It's my experience now.
Of course thanks for the great tool.

**Comment by leodevbro** [comment]
For now, maybe there is some kind of solution for you. You can try hiding all non-focused blocks. First, please make sure VSCode is up to date to the latest, then Go to Blockman settings and type "none" in all 11 depth-color fields from 0 to 10. Also type "none" in N19 (Custom Color Of Block Border) and N20 (Custom Color Of Depth0 Border). depth 0 block is the ground block.

And then maybe you'd like to enable `Editor › Guides: Bracket Pairs` or `Editor › Guides: Indentation` or both.

**Comment by leodevbro** [comment]
@Cicin411,
Blockman 1.4.0 is now released. It supports reversed rendering (from focus block outward or inward) and more. Here is the video instruction for the advanced coloring settings:

https://www.youtube.com/watch?v=UsET6-kPu90

I believe you can achieve your need with one (or some) of these settings:
`N33 A02 B1 From Focus To Outward For All Borders`
`N33 A02 B2 From Focus To Outward For All Backgrounds`

`N33 A04 B1 From Focus To Outward For Focus Tree Borders`
`N33 A04 B2 From Focus To Outward For Focus Tree Backgrounds`

If you find it difficult to adjust the settings exactly for your needs, please let me know and I will help you with the instructions specifically for your case.
