### ISSUE TITLE
Left Padding

### ISSUE THREAD

**Issue by thegreedyturtle** [leodevbro/vscode-blockman#53]
Is there a way to add a pixel or three of padding on the left? It's pretty jarring to have no padding on the box.

**Comment by leodevbro** [comment]
Duplicate issue:
https://github.com/leodevbro/vscode-blockman/issues/16

**Comment by leodevbro** [comment]
@thegreedyturtle, I think I implemented the block-expanding/padding (**only right side**) settings.
The latest version of Blockman is 1.5.1 (2022-01-19).

![right-side-padding-strategies-2-gif](https://user-images.githubusercontent.com/54504880/150204474-647609ad-8428-4762-b276-a84439640b9c.gif)
