### ISSUE TITLE
Option to make all blocks within current scope to be highlighted?

### ISSUE THREAD

**Issue by GanerCodes** [leodevbro/vscode-blockman#54]
Basically, I want the outlines for all blocks. however I also want everything in my current scope to have a different background, here's an example
![image](https://user-images.githubusercontent.com/34655998/143572511-2a239113-cf8f-47b5-a8c2-d1938bf732d1.png)
I want that part to be the custom scope color

**Comment by leodevbro** [comment]
So, you prefer A or B ? Maybe something else?

<img width="616" alt="2021-11-26_21-37-38" src="https://user-images.githubusercontent.com/54504880/143616731-0f1f208b-4436-4731-97bf-b169f54f1792.png">

**Comment by GanerCodes** [comment]
A :)

**Comment by leodevbro** [comment]
Ok, thanks. I'll try to implement this ability in Blockman soon. Maybe several days.

**Comment by leodevbro** [comment]
@GanerCodes,
Blockman 1.4.0 is now released. Here is the video instruction for the advanced coloring settings:

https://www.youtube.com/watch?v=UsET6-kPu90

I believe you can achieve your need with the `N33 A05 B2` setting, it is an advanced coloring setting: `From Focus To Inward For All Backgrounds`, you can play with it and adjust how you want.

If you find it difficult to adjust the settings exactly for your needs, please let me know and I will help you with the instructions specifically for your case.

**Comment by GanerCodes** [comment]
bro ur cracked this looks amazing 
![image](https://user-images.githubusercontent.com/34655998/147395271-a2b26c5e-c48c-4dd7-bdab-84df0a9891ca.png)

**Comment by leodevbro** [comment]
Thanks. Well, I see a bit strange thing in your screenshot. Maybe line height is set to very small? Or maybe too small fontsize?

![2021-12-26_03-23-24](https://user-images.githubusercontent.com/54504880/147395403-1fba66f9-66f0-44bf-8cf6-0990d98f447c.png)

**Comment by GanerCodes** [comment]
Ah, I had editor-zoomed out for the screenshot, like with ctrl mouse wheel rather than ctrl plus; resetting that type of zoom and then doing the full GUI zooming fixed it

**Comment by leodevbro** [comment]
@GanerCodes, Very good news: I fixed the mouse wheel zoom behavior of Blockman. It should work fine now. The latest version of Blockman is `1.4.5 (2022-01-03)`

**Comment by GanerCodes** [comment]
BRO YOUR THE KING
