### ISSUE TITLE
Start with rendering toggled off?

### ISSUE THREAD

**Issue by narfel** [leodevbro/vscode-blockman#55]
Hi, great extension and nice documentation. I have a small request. I have bound a keyboard shortcut to _@command:blockman.toggleEnableDisable_. Is it somehow possible to have the extension enabled but rendering turned off when starting vscode? Although handy, i prefer to have the extension toggled off initially and use it on demand.

**Comment by leodevbro** [comment]
I'll try to implement it soon.

**Comment by leodevbro** [comment]
@narfel,
Blockman 1.4.0 is now released. Here is the video instruction for the advanced coloring settings:

https://www.youtube.com/watch?v=UsET6-kPu90

Also, I added an additional command:
`Press F1 and find "Blockman Toggle Keep Off State After Restarting VSCode"`

So, if you want Blockman to keep off state even after restarting VSCode, you need to do both:

1) activate keeping off state (`Blockman Toggle Keep Off State After Restarting VSCode`)
2) disabled Blockman (`Blockman Toggle Enable/Disable`)

**Comment by narfel** [comment]
Thank you, works perfectly.
