### ISSUE TITLE
Background color still on, even though all background colour settings are none

### ISSUE THREAD

**Issue by pgbarletta** [leodevbro/vscode-blockman#56]
How is this possible? I thought `blockman.n04ColorComboPreset` was supposed to be overridden by the following options.

![image](https://user-images.githubusercontent.com/5693483/144742461-f948b43e-8e34-4a32-977c-86195b60b517.png)

But is actually the only setting that matters:

![image](https://user-images.githubusercontent.com/5693483/144742583-de57d666-881b-4dda-ac01-36fcb2d2b78b.png)

I just want to keep the borders.

Love the extension. Cheers!

**Comment by leodevbro** [comment]
@pgbarletta, Have you updated Blockman to the latest version (1.3.3) ?

**Comment by pgbarletta** [comment]
Yes, I've just downloaded it. 
This is my system:
```
Distributor ID: Neon
Description:    KDE neon User - Plasma 25th Anniversary Edition
Release:        20.04
Codename:       focal
```

and these are my installed extensions:
```
leodevbro.blockman
alefragnani.Bookmarks
xaver.clang-format
ms-vscode.cmake-tools
Shan.code-settings-sync
ms-vscode.cpptools
ms-vscode.cpptools-themes
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
julialang.language-julia
yzhang.markdown-all-in-one
nvidia.nsight-vscode-edition
ms-python.python
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
kamikillerto.vscode-colorize
ms-azuretools.vscode-docker
singularitti.vscode-julia-formatter
ms-python.vscode-pylance
ms-vscode-remote.vscode-remote-extensionpack
wayou.vscode-todo-highlight
VisualStudioExptTeam.vscodeintellicode
```

**Comment by leodevbro** [comment]
So, if I understand correctly, you want also the focused block background to be off? Please try this:
`"blockman.n17CustomColorOfFocusedBlock": "none",`

**Comment by pgbarletta** [comment]
oohhh, now I get it. But if I do that, I loose the borders too. I thought "Color" meant background color.
It'd be nice to be able to just keep the borders, but I can totally manage now.

Thank you for such a quick answer.

**Comment by leodevbro** [comment]
lose borders? No, the borders will be still there. Please copy all your Blockman settings here, so I can see the cause of your issue.

**Comment by pgbarletta** [comment]
Loosing borders:
```
"blockman.n04ColorComboPreset": "Classic Light (Super gradients)",
    "blockman.n05CustomColorOfDepth0": "#none",
    "blockman.n06CustomColorOfDepth1": "#none",
    "blockman.n07CustomColorOfDepth2": "#none",
    "blockman.n08CustomColorOfDepth3": "#none",
    "blockman.n09CustomColorOfDepth4": "#none",
    "blockman.n10CustomColorOfDepth5": "#none",
    "blockman.n11CustomColorOfDepth6": "#none",
    "blockman.n12CustomColorOfDepth7": "#none",
    "blockman.n13CustomColorOfDepth8": "#none",
    "blockman.n14CustomColorOfDepth9": "#none",
    "blockman.n15CustomColorOfDepth10": "#none",
    "blockman.n17CustomColorOfFocusedBlock": "none",
    "blockman.n18CustomColorOfFocusedBlockBorder": "black",
    "blockman.n19CustomColorOfBlockBorder": "black",
    "blockman.n20CustomColorOfDepth0Border": "black"
```
![image](https://user-images.githubusercontent.com/5693483/144745391-63a223cf-c8d2-4784-ad56-34eeb423bf3e.png)


with borders:
```
"blockman.n05CustomColorOfDepth0": "#none",
    "blockman.n06CustomColorOfDepth1": "#none",
    "blockman.n07CustomColorOfDepth2": "#none",
    "blockman.n08CustomColorOfDepth3": "#none",
    "blockman.n09CustomColorOfDepth4": "#none",
    "blockman.n10CustomColorOfDepth5": "#none",
    "blockman.n11CustomColorOfDepth6": "#none",
    "blockman.n12CustomColorOfDepth7": "#none",
    "blockman.n13CustomColorOfDepth8": "#none",
    "blockman.n14CustomColorOfDepth9": "#none",
    "blockman.n15CustomColorOfDepth10": "#none",
    "blockman.n17CustomColorOfFocusedBlock": "#ffffff",
    "blockman.n18CustomColorOfFocusedBlockBorder": "black",
    "blockman.n19CustomColorOfBlockBorder": "black",
    "blockman.n20CustomColorOfDepth0Border": "black"
```

![image](https://user-images.githubusercontent.com/5693483/144745416-8a12822b-3fbd-406c-8da6-24a34481bf4d.png)

The only change I made was from:
```
"blockman.n17CustomColorOfFocusedBlock": "none",
```
to:
```
"blockman.n17CustomColorOfFocusedBlock": "#ffffff",
```

**Comment by leodevbro** [comment]
`#none` is wrong value. Please remove the `#` (hash symbol). If still not solved, please restart VSCode and then make sure that Blockman version is truly `1.3.3`.

**Comment by pgbarletta** [comment]
Done and restarted VSCode.
```
"blockman.n05CustomColorOfDepth0": "none",
    "blockman.n06CustomColorOfDepth1": "none",
    "blockman.n07CustomColorOfDepth2": "none",
    "blockman.n08CustomColorOfDepth3": "none",
    "blockman.n09CustomColorOfDepth4": "none",
    "blockman.n10CustomColorOfDepth5": "none",
    "blockman.n11CustomColorOfDepth6": "none",
    "blockman.n12CustomColorOfDepth7": "none",
    "blockman.n13CustomColorOfDepth8": "none",
    "blockman.n14CustomColorOfDepth9": "none",
    "blockman.n15CustomColorOfDepth10": "none",
    "blockman.n17CustomColorOfFocusedBlock": "none",
    "blockman.n18CustomColorOfFocusedBlockBorder": "black",
    "blockman.n19CustomColorOfBlockBorder": "black",
    "blockman.n20CustomColorOfDepth0Border": "black"
```

![image](https://user-images.githubusercontent.com/5693483/144746834-7cd06d68-f838-469a-97c0-3738c8827854.png)


![image](https://user-images.githubusercontent.com/5693483/144746864-6373dbdb-e7d9-4a88-b7ab-46b5a4154ba0.png)

**Comment by leodevbro** [comment]
I cannot reproduce your issue with your settings. Borders are being rendered fine in my environment:

![2021-12-05_16-46-23](https://user-images.githubusercontent.com/54504880/144747172-02c81c88-1fa5-4920-824f-530540e2a896.png)

**Comment by leodevbro** [comment]
[UPDATE]: Now I reproduced it in my VSCode. It works fine on VSCode Insiders, but not in VSCode. So now I'm trying to find the cause of the issue.

**Comment by leodevbro** [comment]
Well, yeah, I think it's not a bug of Blockman, but it's a bug of VSCode, because it works fine in VSCode Insiders. I'll try to find exact cause of this problem.

**Comment by pgbarletta** [comment]
last vscode release was on october, I'm guessing the bug fix might be around the corner.

**Comment by pgbarletta** [comment]
by the way, the new update did fix it. So it's all good now.
