### ISSUE TITLE
Advanced coloring background settings don't work correctly if the corresponding border setting is not set

### ISSUE THREAD

**Issue by tlemo** [leodevbro/vscode-blockman#58]
For example, the following combination doesn't work:

```
    "blockman.n33A04B1FromFocusToOutwardForFocusTreeBorders": "!40,0,0,0; none > red > green > blue",
    "blockman.n33A04B2FromFocusToOutwardForFocusTreeBackgrounds": "40,0,0,0; none > red > green > blue",
```

Note that if the border setting is enabled, the background will work fine as well. As far as I can tell, the border setting must define at least as many nesting levels as the background in order to have the background work

**Comment by leodevbro** [comment]
Maybe I did not understand the issue well. I guess the combination works fine in my PC.

![2022-01-01_13-16-25](https://user-images.githubusercontent.com/54504880/147847666-cfa7223d-4a91-4eef-a8b3-90b16f7dcb99.png)

**Comment by tlemo** [comment]
Thanks for looking into it. I'll try to narrow down the conditions required to reproduce the problem.

In the meantime, let's close this issue and reopen it if needed.
