### ISSUE TITLE
feature request : quick toggle for enable and disable rendering. 

### ISSUE THREAD

**Issue by qi0727** [leodevbro/vscode-blockman#6]
It'd be nice to be able to have quick toggle for the rendering. sometime jumping up file here and there and the the rendering just pop up is somewhat distracting.  adding a toggle similar to git lens would be prefect. 
![Screenshot 2021-06-08 at 3 22 14 pm](https://user-images.githubusercontent.com/32862453/121141230-53ed8e80-c86d-11eb-889f-9965ad3c4273.png)

**Comment by leodevbro** [comment]
You mean disable/enable Blockman with a command?

**Comment by qi0727** [comment]
yup, instead to going to manage extension  to enable/ disable

**Comment by leodevbro** [comment]
You can set Max Depth to "-1" in Blockman settings, so it will not render anything. You still prefer a vscode command?

**Comment by qi0727** [comment]
that's is similar with going to manage extension to enable/ disable rite ? it required multiple step to achieve render/not render.  

yeah i would be super great if we have the vs code command available.

**Comment by leodevbro** [comment]
I updated Blockman to 1.1.4 version, now you can run toggle command. Hope it will work fine.

**Comment by qi0727** [comment]
updated , it works perfectly ! thanks you so much !
