### ISSUE TITLE
Guides settings reseting every vs code launch

### ISSUE THREAD

**Issue by Dant3s15** [leodevbro/vscode-blockman#61]
Indentation guides  setting in vs code is set to false every time I launch VS code, when I disable blockman extension it stays turned on.

**Comment by leodevbro** [comment]
Now I updated Blockman, latest version is `1.4.6` (2022-01-07).
You can use this quick command:
`Press F1 and find "Blockman Toggle Disable/Enable Automatic Showing/Hiding Indent Guides"`

It will tell Blockman to leave the indent guides alone and to not touch them. So it means, Blockman will not show/hide indent guides automatically, it simply will not touch them, so you will have full manual control of intent guides.

.

Also there is one strange thing, possibly a bug of VSCode. I turn on indent guides, then I restart VSCode, indent guides are still on (in settings) but not showing in actual editor UI. So I have to disable and re-enable indent guides and then they will show up. Do you have this issue too?

**Comment by Dant3s15** [comment]
Thank You! It was driving me crazy to set this every time :)
I don't have the bug that you are mentioning in the last sentence.

pt., 7 sty 2022 o 01:16 Levan Katsadze ***@***.***>
napisał(a):

**Comment by leodevbro** [comment]
I made a VSCode bug report here:
https://github.com/microsoft/vscode/issues/141026
