### ISSUE TITLE
Uninstalling extension leads to removing existing default guide line from vscode

### ISSUE THREAD

**Issue by KaushikSathvara** [leodevbro/vscode-blockman#64]
When I uninstalled blockman extension from my vscode, it also disabled the guides from editor which leads me to reset `settings.json` for vscode.

Here are two properties doesnot set to default after removing extension from `settings.json`

```
"editor.guides.indentation": false,
"editor.guides.bracketPairs": false,
```

**Comment by leodevbro** [comment]
VSCode system currently does not give extensions access to the settings at uninstall event.

https://github.com/microsoft/vscode/issues/45474

<br />
<br />
<br />


That's why I wrote this warning at the top of Blockman info page:

<p><strong>For better experience:</strong> Blockman <strong>WILL CHANGE</strong> these 8 items in VSCode settings (only one-time at the installation event). You can change them again when you want. These 8 settings are very non-vital, so maybe you don't even need to backup them first.</p>

```jsonc
// settings.json (User/Global config, not Workspace config)
// To open this file in VSCode, press F1, type 'settings json' and choose 'Preferences: Open Settings (JSON)'
{
    // ...
    "editor.inlayHints.enabled": false,
    "editor.renderIndentGuides": false, // old API for indent guides
    "editor.guides.indentation": false, // new API for indent guides
    "editor.guides.bracketPairs": false, // new advanced indent guides (This does not turn off editor.bracketPairColorization)
    "editor.wordWrap": "off",
    "diffEditor.wordWrap": "off",

    "workbench.colorCustomizations": {
        // ...
        "editor.lineHighlightBorder": "#9fced11f",
        "editor.lineHighlightBackground": "#1073cf2d"
    }
}
```

**Comment by KaushikSathvara** [comment]
Good, Actually I installed it directly from the extension store and didn't read those warnings, My bad! 
Anyway, I'm closing this issue. 

Thanks.

**Comment by ErikAmerico** [comment]
> VSCode system currently does not give extensions access to the settings at uninstall event.
> 
> 
> 
> https://github.com/microsoft/vscode/issues/45474
> 
> 
> 
> <br />
> 
> <br />
> 
> <br />
> 
> 
> 
> 
> 
> That's why I wrote this warning at the top of Blockman info page:
> 
> 
> 
> <p><strong>For better experience:</strong> Blockman <strong>WILL CHANGE</strong> these 8 items in VSCode settings (only one-time at the installation event). You can change them again when you want. These 8 settings are very non-vital, so maybe you don't even need to backup them first.</p>
> 
> 
> 
> ```jsonc
> 
> // settings.json (User/Global config, not Workspace config)
> 
> // To open this file in VSCode, press F1, type 'settings json' and choose 'Preferences: Open Settings (JSON)'
> 
> {
> 
>     // ...
> 
>     "editor.inlayHints.enabled": false,
> 
>     "editor.renderIndentGuides": false, // old API for indent guides
> 
>     "editor.guides.indentation": false, // new API for indent guides
> 
>     "editor.guides.bracketPairs": false, // new advanced indent guides (This does not turn off editor.bracketPairColorization)
> 
>     "editor.wordWrap": "off",
> 
>     "diffEditor.wordWrap": "off",
> 
> 
> 
>     "workbench.colorCustomizations": {
> 
>         // ...
> 
>         "editor.lineHighlightBorder": "#9fced11f",
> 
>         "editor.lineHighlightBackground": "#1073cf2d"
> 
>     }
> 
> }
> 
> ```

If I didn't back them up on install, if i were to uninstall.. are these the settings I would revert back to?

**Comment by leodevbro** [comment]
@ErikAmerico , These values are Blockmam values, not default values. But you can set these values to default very easily in VS Code settings. You just find each property (you can simply search in vs code settings search field) and click maybe three dots button and set to default value.

**Comment by ErikAmerico** [comment]
@leodevbro thank you!

I really enjoy the amount of customization you allowed. I've only had your extension for like 12 hours. But I think it's awesome so far!
