### ISSUE TITLE
VSCode IPYNB Supper Gradients Color Combo Preset not working.

### ISSUE THREAD

**Issue by ndgayan** [leodevbro/vscode-blockman#65]
The Supper Gradients Color Combo is not expanding to the right side of the notebook cell. Could you come up with a solution to fix this issue? I'm currently using the Monokai color theme in VSCode. Thank you for the amazing work !!!.

![image](https://user-images.githubusercontent.com/1891059/149257336-d641c177-6bb9-4cd9-a0a1-983bade2f653.png)

**Comment by ndgayan** [comment]
Thank you. I will close the issue.

**Comment by leodevbro** [comment]
@ndgayan, I think I implemented the block-expanding settings.
The latest version of Blockman is 1.5.1 (2022-01-19).

![right-side-padding-strategies-2-gif](https://user-images.githubusercontent.com/54504880/150204474-647609ad-8428-4762-b276-a84439640b9c.gif)

**Comment by ndgayan** [comment]
Thank you and kudos for your amazing work.
