### ISSUE TITLE
Allow global enable/disable

### ISSUE THREAD

**Issue by peterloron** [leodevbro/vscode-blockman#67]
This extension is very useful for me in some situations, but I prefer to not have it enabled unless I need help sorting out all the blocks.  :-)

I would like to be able to have the extension installed but not active unless I explicitly toggle it on for a particular project. The current enable/disable quick menu item is good, but I want to be able to set the global default enable/disable as well.

**Comment by leodevbro** [comment]
Hello, have you tried this instruction?
`You can toggle enable/disable: Press F1 and then type "blockman toggle".`

![2022-01-21_23-09-21-222](https://user-images.githubusercontent.com/54504880/150586753-71b0dccf-f23e-4f6a-a306-a9ca784abd95.png)


Also, have you tried these quick commands?

```
Press F1 and find "Blockman Toggle Enable/Disable"
Press F1 and find "Blockman Toggle Keep Off State After Restarting VSCode"
Press F1 and find "Blockman Toggle Disable/Enable Automatic Showing/Hiding Indent Guides"
```

![2022-01-21_23-09-51-333](https://user-images.githubusercontent.com/54504880/150586775-99d9fb06-7744-45fc-b5fa-c1fc6ca6d32d.png)


So, I guess, you want Blockman to keep OFF state after restarting VSCode, right?
In that case, I think you can use the `Keep Off State After Restarting VSCode` command.
