### ISSUE TITLE
I want Keep the background of theme，only show borders

### ISSUE THREAD

**Issue by dmfan** [leodevbro/vscode-blockman#77]
I set like the suggestion ,but don not work.

![image](https://user-images.githubusercontent.com/27176097/159145169-ec23dcc6-eeee-4b41-bb1a-4cdc8d0cf63a.png)

![image](https://user-images.githubusercontent.com/27176097/159145199-d1f73950-6341-4a3b-ac91-795c02a9a8e1.png)

**Comment by leodevbro** [comment]
Hello, it strange. It works in my machine. Please try updating and restarting VSCode.

Also, please copy paste the `settings.json` file here, so I will be able to investigate the issue more deeply.
(press F1, type 'settings json' and choose `Preferences: Open Settings (JSON)`)

**Comment by dmfan** [comment]
Thank you very much .

I fix it after i update vscode to 1.65.2
