### ISSUE TITLE
Vertical Color Scale

### ISSUE THREAD

**Issue by RCVarley** [leodevbro/vscode-blockman#79]
I work in Vue Single File Components that are structured like so:

```vue
<template></template>
<script>
export default {
  components: {
    // block 0 (colour 0)
  },
  data() {
    // block 1 (colour 1)
  },
  methods: {
    // block 2 (colour 2)
  },
  // 'n' number other properties/blocks
};
</script>
<style></style>
```

What I want is to highlight `components`, `data`, `methods`, and any other property on that level in a different colour.

Is this kind of feature something you'd be willing to implement? Or maybe it's something I can achieve with the current feature-set?

**Comment by leodevbro** [comment]
Hi, maybe you want something like this?

```
"blockman.n33A01B1FromDepth0ToInwardForAllBorders": "10,0,0,0; none > none > neutral > rgb(40, 90, 240)",
"blockman.n33A01B2FromDepth0ToInwardForAllBackgrounds": "10,0,0,0; none > none > neutral > rgb(40, 50, 90)",
```

![2022-05-10_19-17-07](https://user-images.githubusercontent.com/54504880/167663907-30e5fd20-a2d9-4c19-b7ee-6b8cb75f5e80.png)

**Comment by RCVarley** [comment]
Ooh, that's nice!

It's not quite the perfect solution, but it certainly helps a lot! Thank you!
