### ISSUE TITLE
Flag to support only highlight the current block or active block

### ISSUE THREAD

**Issue by sujeet-agrahari** [leodevbro/vscode-blockman#80]
By default it highlights all the block and sub-blocks which overrides selected theming colors.

Can we have flag which could set whether it should target only the active block or nested?

**Comment by leodevbro** [comment]
Yes, I think Blockman has many settings to do various of colorings.

Example 1:
```
"blockman.n33A01B1FromDepth0ToInwardForAllBorders": "10,0,0,1; none",
"blockman.n33A01B2FromDepth0ToInwardForAllBackgrounds": "10,0,0,1; none",
```
![2022-05-18_12-08-48](https://user-images.githubusercontent.com/54504880/168992279-fd7e4ac1-00d3-436e-afcb-71eb8b5e1c25.png)

<br />
<br />


Example 2:
```
"blockman.n33A01B1FromDepth0ToInwardForAllBorders": "10,0,0,1; none",
"blockman.n33A01B2FromDepth0ToInwardForAllBackgrounds": "10,0,0,1; none",

"blockman.n33A05B2FromFocusToInwardForAllBackgrounds": "50,0,0,1; rgb(8, 22, 33)",
```
![2022-05-18_12-11-30](https://user-images.githubusercontent.com/54504880/168992368-314f2bf9-5340-49fd-afa0-78f9887dcd9f.png)

<br />
<br />


Example 3:
```
"blockman.n33A01B1FromDepth0ToInwardForAllBorders": "10,0,0,1; none",
"blockman.n33A01B2FromDepth0ToInwardForAllBackgrounds": "10,0,0,1; none",

"blockman.n33A05B2FromFocusToInwardForAllBackgrounds": "50,0,0,1; rgb(8, 22, 33) > red > green"
```
![2022-05-18_12-16-25](https://user-images.githubusercontent.com/54504880/168992472-ab5f2c94-0c25-4f60-a448-112e1d00fc14.png)

**Comment by sujeet-agrahari** [comment]
@leodevbro Thanks. Example 2 works. It's not exactly what I wanted. But It will work.

**Comment by leodevbro** [comment]
Feel free to add some more details for your need, so I will be able to understand it more clearly and maybe provide a better solution.

**Comment by sujeet-agrahari** [comment]
Currenltly with above configuration, example 2, it highlights tand adds background to the current selected block. But, it also puts border on all blocks and nested blocks.

I don't want those borders, I only want a background color on the selected block.

**Comment by leodevbro** [comment]
You mean in your machine it is not showing the same way as my screenshot? Nested blocks should not have borders with the configuration of example 2. Maybe you have changed some other advanced coloring settings. Can you screenshot the blocks and also copy-paste all the settings of Blockman from settings.json file?

Before that, maybe you can try elevating the priorities of these settings like this:

```
"blockman.n33A01B1FromDepth0ToInwardForAllBorders": "200,0,0,1; none",
"blockman.n33A01B2FromDepth0ToInwardForAllBackgrounds": "200,0,0,1; none",

"blockman.n33A05B2FromFocusToInwardForAllBackgrounds": "250,0,0,1; rgb(8, 22, 33)",
```

**Comment by sujeet-agrahari** [comment]
It worked now perfectly. There some setting populated as a result of my tries I guess. I cleaned and add above lines. Thanks, I was exactly looking for this.

Just one thing what about dropping some nice shadow onto the selected block?

**Comment by leodevbro** [comment]
For padding, Blockman has only right-side padding settings, please search "padding" in Blockman page. There you can see the GIF instruction.

For shadow, it's kinda problematic, because CSS is very limited in VS Code extension environment. Maybe I will be able to implement HTML `SVG` blocks instead of currently implemented HTML `div` Blocks in the future to make the styling more flexible.
