### ISSUE TITLE
[Question] How do I disable background colors for blocks?

### ISSUE THREAD

**Issue by WHMHammer** [leodevbro/vscode-blockman#85]
Hi, I'd like to disable background colors for the blocks (use the same vscode theme-defined background color for all blocks) but keep the block borders. How shall I do so? Thank you!

**Comment by leodevbro** [comment]
Please see the "keep only borders" section in Blockman page. If you still need help, feel free to comment here with more details.

**Comment by WHMHammer** [comment]
I should have checked the REAME first... That solved my problem. Thank you so much!
