### ISSUE TITLE
Feature Request: Option to Enable/Disable Box Edges

### ISSUE THREAD

**Issue by KirbyBarba** [leodevbro/vscode-blockman#9]
Please provide an option to selectively enable/disable the 4 box edges. For example, I prefer to only have the left edge of a code block rendered.

Thank you!

**Comment by leodevbro** [comment]
I think it's possible with some work, but isn't it the same as just vertical indent lines? This is not very philosophy of Blockman. Maybe I'll think about it if this feature request have at least 20 likes.

**Comment by KirbyBarba** [comment]
Never mind, I found another extension that has this feature. Thanks.
