### ISSUE TITLE
Preset for different color themes

### ISSUE THREAD

**Issue by NN---** [leodevbro/vscode-blockman#92]
It would be nice to have 2 presets, one for VSC dark theme mode, another for VSC light mode.
When I switch system theme with VSC theme changed automatically, but the Blockman cannot do it too

**Comment by leodevbro** [comment]
When I switch dark/light theme of VS Code, Blockman automatically adjusts blockman color combo.
![vs-code - blockman - theme switch](https://user-images.githubusercontent.com/54504880/199001416-12ae9ad7-9fa1-463d-804f-872bf619252a.gif)

Please check what values do you have in these 4 settings of Blockman?
![image](https://user-images.githubusercontent.com/54504880/199001538-4079a143-b4e1-41b9-9635-e8653a871e55.png)

**Comment by NN---** [comment]
This worked!
Thanks!

Probably this was not the default, or I destroyed it.
