### ISSUE TITLE
Extension not loading - againg?

### ISSUE THREAD

**Issue by holoubl** [leodevbro/vscode-blockman#93]
**Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No**

A have tha same issue.
Do not use parent colorize.
![obrazek](https://user-images.githubusercontent.com/97892136/199424424-a7d006fb-484a-4245-b045-b46fb6d177ce.png)
Use these extensions and there is no error in the log.
love this extension.
thanks ludek

**Comment by leodevbro** [comment]
Hi, I'll answer here:
https://github.com/leodevbro/vscode-blockman/issues/8

**Comment by leodevbro** [comment]
Please show me the settings json files of `User` and `Workspace`.
![image](https://user-images.githubusercontent.com/54504880/199612556-dc5cafda-ec1d-48b4-8aee-7b7f1f0193fd.png)

**Comment by holoubl** [comment]
![obrazek](https://user-images.githubusercontent.com/97892136/199668637-85be4571-566e-453f-8818-2615f71b3ef9.png)
It happens in all my projects, workspaces. I am attaching a settings of one of them.

**Comment by holoubl** [comment]
![obrazek](https://user-images.githubusercontent.com/97892136/199675009-e8583317-df0e-43f1-8ceb-ac4b70847e55.png)
with new VSCode update the block man works again. From today.
